### ISSUE TITLE
Testcard

### ISSUE THREAD

**Issue by ghost** [Climate101Utrecht/MOOC#2]
Test

**Comment by SanliFaez** [comment]
what are you testing @SanderVanHolsteijn ? 
Sanli here, feeling good to be in contact with such an active group of students :)

**Comment by ghost** [comment]
Hi Sanli, I tried creating a card for the first time, and called it Testcard :). Haven't figured out a way to remove it yet, do you know how? I'm looking forward to the process as well.

**Comment by SanliFaez** [comment]
you can close the issue when it is no more relevant.
